#!/bin/bash
# /etc/init.d/picar

### BEGIN INIT INFO
# Provides:          picar
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Pi Car
# Description:       This service is used to manage a servo
### END INIT INFO

start() {
    echo "Starting picar"
    cd /home/pi/picar/
    sudo -u pi ./picar >& /home/pi/picar/log &
    chown pi:pi /home/pi/picar/log
}

stop() {
    echo "Stopping picar"
    kill $(cat /home/pi/picar/pid)
}

case "$1" in 
    start)
	start
        ;;
    stop)
	stop
        ;;
    restart)
	stop
	start
	;;
    *)
        echo "Usage: /etc/init.d/picar start|stop|restart"
        exit 1
        ;;
esac

exit 0
